### ISSUE TITLE
Impossible de compiler avec gradle

### ISSUE THREAD

**Issue by guillaumeblaquiere** [tsegismont/vertx-kotlin-music#2]
Juste après un git clone, j'ai lancé un build sur Cloud Shell et ca ne marche pas. Une idée de ce qui manque? Une dépendance?

guillaume_blaquiere@cloudshell:~/vertx-kotlin-music😎 ./gradlew jibDockerBuild --image=gcr.io/gbl-imt-homerider-basguillaueb/vkm
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :web:jibDockerBuild
Containerizing application to Docker daemon as gcr.io/gbl-imt-homerider-basguillaueb/vkm...
Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
Executing tasks:
[======                        ] 20.0% complete
> building dependencies layer
> building resources layer
> building project dependencies layer
> building classes layer
> Task :web:jibDockerBuild FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':web:jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri(Z)Lorg/apache/http/client/config/Reque
stConfig$Builder;
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 6s
6 actionable tasks: 6 executed

**Comment by tsegismont** [comment]
J'ai découvert ce problème juste avant de présenter hier.

Tu peux faire un checkout de la branche latest-stable en attendant

Si tu as une idée pour ce problème je suis preneur !

**Comment by tsegismont** [comment]
@guillaumeblaquiere en mettant toutes les définitions de plugins dans le fichier de build racine, ça semble fonctionner. Tu peux confirmer en revenant sur `master`?

**Comment by guillaumeblaquiere** [comment]
@tsegismont, non pas vraiment. j'ai toujours des erreurs.

En mettant que les plugin (en supprimant le `apply false`)
```
guillaume_blaquiere@cloudshell:~/vertx-kotlin-music😎 ./gradlew jibDockerBuild --image=gcr.io/gbl-imt-homerider-basguillaueb/vkm

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'vertx-kotlin-music'.
> Extension property vertx.mainVerticle must be specified when using io.vertx.core.Launcher as a launcher

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

Et en ajoutant la définition de vertx
```
val launcher_class = "io.github.tsegismont.vkm.Main"
val jvm_flags = listOf("-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory")

vertx {
  vertxVersion = "3.8.4"
  launcher = launcher_class
  mainVerticle = "io.github.tsegismont.vkm.App"
  jvmArgs = jvm_flags
}
```

J'obtiens cette nouvelle erreur
```
guillaume_blaquiere@cloudshell:~/vertx-kotlin-music😎 ./gradlew jibDockerBuild --image=gcr.io/gbl-imt-homerider-basguillaueb/vkm
Could not resolve compiler classpath. Check if Kotlin Gradle plugin repository is configured in root project 'vertx-kotlin-music'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Could not resolve all files for configuration ':kotlinCompilerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.61 because no repositories are defined.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

Et comme j'ai toujours fait du Maven et jamais du gradle, je suis un peu light pour débugger!

**Comment by tsegismont** [comment]
> En mettant que les plugin (en supprimant le apply false)

Si tu enlèves apply false, chaque plugin s'applique au projet racine. Y compris le vertx plugin donc, qui va chercher le main verticle qui n'est pas défini à cet endroit.
D'où ce premier message d'erreur:

```
Extension property vertx.mainVerticle must be specified when using io.vertx.core.Launcher as a launcher
```

>Et en ajoutant la définition de vertx
>J'obtiens cette nouvelle erreur

Gradle commence par établir la configuration des plugins qui s'appliquent au projet. En ajoutant la définition de vertx tu as résolu le problème précédent mais du coup Gradle cherche à compiler le project racine. Or il n'y a pas de définition de `repositories` (jcenter, central, ... etc) du coup il ne sait pas où aller chercher les dépendances.
D'où ce deuxième message d'erreur:

```
Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.61 because no repositories are defined.
```

Je viens de re-tester sur `master` et ça fonctionne pour moi. Dans le doute j'ai fait un checkout dans un autre répertoire, ça marche aussi.

Tu peux ré-essayer en enlevant tes modifications ?

**Comment by guillaumeblaquiere** [comment]
Ok, j'ai tout dégagé, fait un nouveau git clone et c'est passé de suite!!

**Comment by tsegismont** [comment]
👍
